const ShopActionTypes = {
  FETCH_COLLESTIONS_START: "FETCH_COLLESTIONS_START",
  FETCH_COLLESTIONS_SUCCESS: "FETCH_COLLESTIONS_SUCCESS",
  FETCH_COLLESTIONS_FAILURE: "FETCH_COLLESTIONS_FAILURE",
};

export default ShopActionTypes;
